[naverpost_hypebeast_fashion]
title = "네이버 포스트 ─ 하입비스트 ─ 패션"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=325345&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_footwear]
title = "네이버 포스트 ─ 하입비스트 ─ 신발"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=325346&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_music]
title = "네이버 포스트 ─ 하입비스트 ─ 음악"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=325347&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_art]
title = "네이버 포스트 ─ 하입비스트 ─ 미술"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=351637&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_tech]
title = "네이버 포스트 ─ 하입비스트 ─ 전자"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=512894&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_automotive]
title = "네이버 포스트 ─ 하입비스트 ─ 자동차"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=366726&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_entertainment]
title = "네이버 포스트 ─ 하입비스트 ─ 엔터테인먼트"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=325427&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_design]
title = "네이버 포스트 ─ 하입비스트 ─ 디자인"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=533592&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_food-beverage]
title = "네이버 포스트 ─ 하입비스트 ─ 음식"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=325348&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_gaming]
title = "네이버 포스트 ─ 하입비스트 ─ 게임"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=624441&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_travel]
title = "네이버 포스트 ─ 하입비스트 ─ 라이프스타일"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=336645&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_hypebeast_sports]
title = "네이버 포스트 ─ 하입비스트 ─ 스포츠"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=351631&memberNo=37600247"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
